### ISSUE TITLE
 PermissionError: [Errno 13] Permission denied: 'cargo'

### ISSUE THREAD

**Issue by zhanghui-china** [lvyufeng/ChatPDF#1]
WSL ubuntu 22.04

git clone https://github.com/lvyufeng/chatpdf
cd chatpdf
conda create -n chatpdf python=3.9 -y
conda activate chatpdf
pip install -r requirements.txt
<img width="1267" alt="eb944d67a21adeffc112c50b2e594b2" src="https://github.com/lvyufeng/ChatPDF/assets/63148804/17ccec42-3a72-41a2-ba64-b2d1960bdfb3">

**Comment by zhanghui-china** [comment]
```
(chatpdf37) zhanghui@zhanghui:~/chatpdf$ pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting mindspore
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/50/f8/28d40344fe7edf482768d5a5eed7f02706894f9f50c1d4942419251d2dbf/mindspore-2.2.14-cp37-cp37m-manylinux1_x86_64.whl (742.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 742.8/742.8 MB 4.5 MB/s eta 0:00:00
Collecting mindnlp
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/62/be/623bb9ad2735599dacf59bde5a6e6cb7b30d656a07afd5a590515ff31389/mindnlp-0.3.0-py3-none-any.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 4.0 MB/s eta 0:00:00
Collecting PyMuPDF
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/11/11/3b33290b8f7046a761e11d4bffd032a1f21e84638e2002ebd44d16e3c402/PyMuPDF-1.22.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 6.2 MB/s eta 0:00:00
Collecting ms2vec
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/aa/3c/cf8c1ce44c3818949bf92a9b2b3f5e67097492c62af38a15e18dacbbf126/ms2vec-0.0.1-py3-none-any.whl (25 kB)
Collecting msimilarities
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/aa/99/cd0a8e1b80bf1375422603a9db0280f2b7af46b80d70b8c817980b9706f0/msimilarities-0.0.2-py3-none-any.whl (25 kB)
Collecting logru
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/61/e5/e01b9a5d64410d9dc16c16dacfbcf30919e2b1ab25577cad83467292c1f7/logru-0.1.0.tar.gz (4.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Checking for Rust toolchain....
      Traceback (most recent call last):
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-km_v17x8/overlay/lib/python3.7/site-packages/maturin/__init__.py", line 140, in prepare_metadata_for_build_wheel
          output = subprocess.check_output(["cargo", "--version"]).decode(
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/subprocess.py", line 411, in check_output
          **kwargs).stdout
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/subprocess.py", line 488, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "/home/zhanghui/anaconda3/envs/chatpdf37/lib/python3.7/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'cargo'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(chatpdf37) zhanghui@zhanghui:~/chatpdf$
```

**Comment by lvyufeng** [comment]
logru安装不了应该是你环境的问题

**Comment by yiluzhuimeng** [comment]
请问解决了吗
